### PR TITLE
Camera Feature

### PR DESCRIPTION
**Pull request by dusty-commits**
- Showing the camera preview
- Showing the drawing overlay
- Freeze framing the composite images and deleting it

You can view a movie of the functionality here: https://drive.google.com/file/d/15ur97QrEhBtP2xiowGC5wC5L14z2-3vF/view?usp=sharing

camera-overlay2

### CODE REVIEW

**Comment by dusty-commits** [comment]
@am-MongoDB Feel free to review, approve (or not) and merge this when you  get a chance. Thanks

**Comment by am-MongoDB** [comment]
I got this crash when I tried testing the PR:
2019-11-23 08:19:55.268464+0000 DrawPad[31024:1890802] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by dusty-commits** [comment]
> I got this crash when I tried testing the PR:
> 2019-11-23 08:19:55.268464+0000 DrawPad[31024:1890802] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

There should be an info.plist committed. One sec. I'll fix it and push.

**Comment by dusty-commits** [comment]
That's wild. My iPad still doesn't crash without it, but I definitely had to do this the first time around. I don't trust my device anymore. Can you run through it once on your end? Sorry about that

**Comment by am-MongoDB** [comment]
Adding it to the plist fixed it - seeing if I managed to get that change included - will merge and check

**Comment by am-MongoDB** [comment]
The problem may have been with my local merging. I'm trying again with the new master

**Comment by am-MongoDB** [comment]
The only remaining problem was a breakpoint I'd left in. I've now removed that so all good

**Pull request merged**
